# Flutter CI — build release APK and upload artifact
name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_apk:
    name: Build Android APK
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      PROJECT_DIR: zoomubik   # <- ajusta aquí si tu proyecto está en otra carpeta; si está en la raíz, deja vacío ''

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Show repo root (debug)
        run: |
          echo "PWD: $(pwd)"
          ls -la

      - name: Install dependencies
        run: |
          if [ -n "$PROJECT_DIR" ]; then
            echo "Using project dir: $PROJECT_DIR"
            cd "$PROJECT_DIR"
          else
            echo "Using repo root as project dir"
          fi
          flutter pub get

      - name: Setup signing (optional, from Secrets)
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          if [ -n "$PROJECT_DIR" ]; then cd "$PROJECT_DIR"; fi
          if [ -n "$KEYSTORE_BASE64" ]; then
            mkdir -p android/app
            echo "$KEYSTORE_BASE64" | base64 --decode > android/app/key.jks
            printf "storePassword=%s\nkeyPassword=%s\nkeyAlias=%s\nstoreFile=app/key.jks\n" "$KEYSTORE_PASSWORD" "$KEY_PASSWORD" "$KEY_ALIAS" > android/key.properties
            echo "Keystore and key.properties created"
          else
            echo "No keystore secret provided — building unsigned APK"
          fi

      - name: Build APK (release)
        run: |
          if [ -n "$PROJECT_DIR" ]; then cd "$PROJECT_DIR"; fi
          flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: zoomubik-apk
          path: |
            ${PROJECT_DIR:+${PROJECT_DIR}/}build/app/outputs/flutter-apk/*.apk
